using System.Collections.Generic;
using ATMTECH.Administration.Services.Interface;
using ATMTECH.Administration.Views.Base;
using ATMTECH.Administration.Views.Interface;
using ATMTECH.Entities;

namespace ATMTECH.Administration.Views
{
    public class DefaultMasterPresenter : BaseAdministrationPresenter<IDefaultMasterPresenter>
    {
        public IGenerateDataEditorService GenerateDataEditorService { get; set; }

        public DefaultMasterPresenter(IDefaultMasterPresenter view)
            : base(view)
        {
        }

        public override void OnViewLoaded()
        {
            User user = AuthenticationService.AuthenticateUser;
            View.IsLogged = user != null && user.IsAdministrator;
        }


        public void GenerateEntityInformation()
        {
            Dictionary<string, string> dictionary =
               GenerateDataEditorService.GetAllEntityInformationToDictionnary(@"C:\Dev\Atmtech\ATMTECH.ShoppingCart.PubJL\bin");
            foreach (KeyValuePair<string, string> keyValuePair in dictionary)
            {
                GenerateDataEditorService.AutoGenerateDataModel(keyValuePair.Key, keyValuePair.Value);
            }
        }

        public void GenerateDatabaseAchievement()
        {
            
        }



    }
}

