using System.Collections.Generic;
using ATMTECH.Entities;

namespace ATMTECH.Administration.Services.Interface
{
    public interface IGenerateDataEditorService
    {
        
        Dictionary<string, string> GetAllEntityInformationToDictionnary(string binDirectory);
        int SaveEntityInformation(EntityInformation entityInformation);
        EntityInformation GetEntityInformation(string entityName);

        void SaveEntityProperty(EntityProperty entityProperty);
        IList<EntityProperty> GetPropertyFromEntityInformation(int id);

        void AutoGenerateDataModel(string nameSpace, string entity);

        void CreatePage(string pageAspx, string nameSpace, IList<EntityProperty> entityProperties,
                        string dataEditorDirectory);

        IList<EntityInformation> GetAllEntityInformation();
    }
}
